# This workflow exists because my readme file is a html file on my machine, I'm developing my readme as html and when I push, this workflow runs a Java fil√© that rename from README.html to README.md, and so it can be recognized by GitHub as readme file
name: Renamer script
on: [ push ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup checkout action 
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Java renamer
        run: java gabrielmjr/script/Util.java

      - name: Commit renamed file
        run: |
             git config --local user.email "action@github.com"
             git config --local user.name "GitHub Actions"
             git add -A
             git commit -m "Renamed README.html to README.md"

      - name: Push updates
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
